<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Rakesh-Singh" failures="1" tests="7" name="Open cart Register Test" time="24.444" errors="0" timestamp="20 Jul 2024 01:12:08 GMT">
  <testcase classname="com.qa.opencart.tests.RegisterTest" name="userRegisterTest" time="3.136"/>
  <testcase classname="com.qa.opencart.tests.RegisterTest" name="userRegisterTest" time="2.287"/>
  <testcase classname="com.qa.opencart.tests.RegisterTest" name="userRegisterTest" time="3.025"/>
  <testcase classname="com.qa.opencart.tests.RegisterTest" name="userRegisterTest" time="2.471">
    <skipped/>
  </testcase> <!-- userRegisterTest -->
  <testcase classname="com.qa.opencart.tests.RegisterTest" name="userRegisterTest" time="2.404">
    <skipped/>
  </testcase> <!-- userRegisterTest -->
  <testcase classname="com.qa.opencart.tests.RegisterTest" name="userRegisterTest" time="1.257">
    <skipped/>
  </testcase> <!-- userRegisterTest -->
  <testcase classname="com.qa.opencart.tests.RegisterTest" name="userRegisterTest" time="1.569">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at com.qa.opencart.tests.RegisterTest.userRegisterTest(RegisterTest.java:53)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- userRegisterTest -->
</testsuite> <!-- Open cart Register Test -->
